### PR TITLE
fix: allow remotePatterns to be overridden

### LINKED ISSUE #110: Image `remotePatterns` in `nextConfig` is not working
### Description

Application is throwing the following error:

```
Error: Invalid src prop (https://randomuser.me/api/portraits/men/4.jpg) on `next/image`, hostname "randomuser.me" is not configured under images in your `next.config.js`
See more info: https://nextjs.org/docs/messages/next-image-unconfigured-host
```

Remote pattern is also configured for the host. Here's my nextConfig:

```mjs
/** @type {import('next').NextConfig} */
import withSnapWP from '@snapwp/next/withSnapWP';

const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'randomuser.me',
      },
    ],
  },
  transpilePackages: ['@workspace/ui'],
};

export default await withSnapWP(nextConfig);
```

### Link to the code that reproduces this issue

https://github.com/kulterryan/snap-wp-test

### To Reproduce

1. Update the nextConfig as following:

```mjs
/** @type {import('next').NextConfig} */
import withSnapWP from '@snapwp/next/withSnapWP';

const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'randomuser.me',
      },
    ],
  },
};

export default await withSnapWP(nextConfig);
```

2. Add Image on the application from randomuser.me
3. That's all, you'll see the error.

### Additional context

_No response_

### Frontend Environment

```bash

```

### Backend Environment

```markdown
<details>
  <summary>Site Health Info</summary>
  <!-- Please leave one blank line below for enabling the code block rendering. -->

  
`
### wp-core ###

version: 6.7.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/u377242068/domains/blog.superpeper.com/public_html
wordpress_size: 56.99 MB (59756736 bytes)
uploads_path: /home/u377242068/domains/blog.superpeper.com/public_html/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /home/u377242068/domains/blog.superpeper.com/public_html/wp-content/themes
themes_size: 22.22 MB (23302138 bytes)
plugins_path: /home/u377242068/domains/blog.superpeper.com/public_html/wp-content/plugins
plugins_size: 24.08 MB (25251867 bytes)
fonts_path: /home/u377242068/domains/blog.superpeper.com/public_html/wp-content/uploads/fonts
fonts_size: directory not found
database_size: 2.28 MB (2392064 bytes)
total_size: 105.57 MB (110702805 bytes)

### wp-active-theme ###

name: Blocksy (blocksy)
version: 2.0.90 (latest version: 2.0.91)
author: CreativeThemes
author_website: https://creativethemes.com
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, responsive-embeds, html5, title-tag, custom-logo, lifterlms-sidebars, boostify-header-footer, rank-math-breadcrumbs, fl-theme-builder-headers, fl-theme-builder-footers, fl-theme-builder-parts, editor-styles, editor-style, editor-color-palette, editor-gradient-presets, post-thumbnails, menus, align-wide, customize-selective-refresh-widgets, header-footer-elementor, widgets
theme_path: /home/u377242068/domains/blog.superpeper.com/public_html/wp-content/themes/blocksy

### wp-themes-inactive (3) ###

Twenty Twenty-Five: version: 1.0, author: the WordPress team (latest version: 1.1)
Twenty Twenty-Four: version: 1.3, author: the WordPress team
Twenty Twenty-Three: version: 1.6, author: the WordPress team

### wp-mu-plugins (1) ###

Hostinger Smart Auto Updates: version: 1.0.6, author: Hostinger

### wp-plugins-active (6) ###

Hostinger Easy Onboarding: version: 2.0.65, author: Hostinger (latest version: 2.0.66)
Hostinger Tools: version: 3.0.28, author: Hostinger (latest version: 3.0.29)
LiteSpeed Cache: version: 6.5.4, author: LiteSpeed Technologies
SnapWP - Helper: version: 0.2.0, author: rtCamp
WPGraphQL: version: 2.0.0, author: WPGraphQL
WPGraphQL Content Blocks: version: 4.8.0, author: WP Engine

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1809
imagemagick_version: ImageMagick 7.1.1-19 Q16-HDRI x86_64 21601 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 2 TB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 196608
	imagick::RESOURCETYPE_MAP: 1,006 GB
	imagick::RESOURCETYPE_MEMORY: 503 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, A, AAI, AI, APNG, ART, ARW, ASHLAR, AVI, AVIF, AVS, B, BAYER, BAYERA, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, C, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FARBFELD, FAX, FF, FILE, FITS, FL32, FLV, FRACTAL, FTP, FTS, FTXT, G, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HEIC, HEIF, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K, K25, KDC, LABEL, M, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MPO, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, O, ORA, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PHM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, QOI, R, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RSVG, RW2, SCR, SCREENSHOT, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, STRIMG, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, Y, YAML, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.18.0-553.34.1.lve.el8.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 8.2.27 64bit
php_sapi: litespeed
max_input_variables: 5000
time_limit: 300
memory_limit: 512M
max_input_time: 240
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 8.11.0 OpenSSL/1.1.1w
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
current: 2025-03-02T15:55:35+00:00
utc-time: Sunday, 02-Mar-25 15:55:35 UTC
server-time: 2025-03-02T15:55:32+00:00

### wp-database ###

extension: mysqli
server_version: 10.11.10-MariaDB
client_version: mysqlnd 8.2.27
max_allowed_packet: 1073741824
max_connections: 2000

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/u377242068/domains/blog.superpeper.com/public_html/wp-content
WP_PLUGIN_DIR: /home/u377242068/domains/blog.superpeper.com/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
fonts: not writable
mu-plugins: writable

`
  
</details>
```

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### PR DESCRIPTION
**Pull request by ayushnirwal**
## What

Allows users to add to remote patterns.

### Related Issue(s):

- Fixes #110 

## Screenshots

N/A

## Additional Info

N/A

## Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/rtCamp/snapwp/blob/develop/.github/CONTRIBUTING.md).
-   [x] My code is tested to the best of my abilities.
-   [x] My code passes all lints (ESLint, tsc, prettier etc.).
-   [x] My code has detailed inline documentation.
-   [ ] I have added unit tests to verify the code works as intended.
-   [ ] I have updated the project documentation as needed.
-   [x] I have added a changeset for this PR using `npm run changeset`.

### CODE REVIEW

File: packages/next/src/config/with-snap-wp.ts [hunk 1]
```diff
@@ -118,6 +118,7 @@ const withSnapWP = async ( nextConfig?: NextConfig ): Promise< NextConfig > => {
 					protocol: 'https',
 					hostname: homeUrl.hostname,
 				},
+				...( ( nextConfig && nextConfig[ 'remotePatterns' ] ) || [] ),
```
Comment (SH4LIN) [inline packages/next/src/config/with-snap-wp.ts:121]:
```JS
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'randomuser.me',
      },
    ],
  },
  transpilePackages: ['@workspace/ui'],
};
```
passing this as a nextConfig will not work with this `...( ( nextConfig && nextConfig[ 'remotePatterns' ] ) || [] ),`

Comment (SH4LIN) [reply packages/next/src/config/with-snap-wp.ts:121]: You'll have to de structure images and and remotePatterns individually, something like this

```
images: {
                        ...( ( nextConfig && nextConfig[ 'images' ] ) || {} ),
			remotePatterns: [
				{
					protocol: 'http',
					hostname: homeUrl.hostname,
				},
				{
					protocol: 'https',
					hostname: homeUrl.hostname,
				},
				...( ( nextConfig && nextConfig[ 'remotePatterns' ] ) || [] ),
                            ]
}
```

**Review by SH4LIN — CHANGES_REQUESTED** [review]

File: packages/next/src/config/with-snap-wp.ts (hunk 1 above)
Comment (justlevine) [reply packages/next/src/config/with-snap-wp.ts:121]: Why can't the HOC do this for us?

Comment (ayushnirwal) [reply packages/next/src/config/with-snap-wp.ts]: @justlevine Which HOC?

File: packages/next/src/config/with-snap-wp.ts [hunk 2]
```diff
@@ -106,6 +106,12 @@ const withSnapWP = async ( nextConfig?: NextConfig ): Promise< NextConfig > => {
 	setConfig();
 	const homeUrl = new URL( getConfig().homeUrl );
 
+	const userImages = nextConfig && nextConfig.images ? nextConfig.images : {};
+	const userRemotePatterns =
```
Comment (SH4LIN) [inline packages/next/src/config/with-snap-wp.ts:110]: Can't we directly use userImages here? If we use userImages variable here we only have to check userImages.remotePatterns if it is not there then use empty array

**Review by SH4LIN — CHANGES_REQUESTED** [review]

File: packages/next/src/config/with-snap-wp.ts (hunk 2 above)
Comment (ayushnirwal) [reply packages/next/src/config/with-snap-wp.ts:110]: Yes!

File: packages/next/src/config/with-snap-wp.ts [hunk 3]
```diff
@@ -106,6 +106,12 @@ const withSnapWP = async ( nextConfig?: NextConfig ): Promise< NextConfig > => {
 	setConfig();
 	const homeUrl = new URL( getConfig().homeUrl );
 
+	const userImages = nextConfig && nextConfig.images ? nextConfig.images : {};
```
Comment (SH4LIN) [inline packages/next/src/config/with-snap-wp.ts:109]: Can we refactor this to `nextConfig?.images ?? {};`?

Same for userRemotePatterns.

**Review by SH4LIN — CHANGES_REQUESTED** [review]

File: packages/next/src/config/with-snap-wp.ts (hunk 1 above)
Comment (SH4LIN) [reply packages/next/src/config/with-snap-wp.ts]: @justlevine Since this thread requires your response, I am keeping it open.

File: packages/next/src/config/with-snap-wp.ts (hunk 3 above)
Comment (SH4LIN) [reply packages/next/src/config/with-snap-wp.ts]: @ayushnirwal One last feedback.

File: packages/next/src/config/with-snap-wp.ts (hunk 1 above)
Comment (justlevine) [reply packages/next/src/config/with-snap-wp.ts]: I'm referring to `withSnapWP( nextConfig )` and trying to get clarification from a user POV (i.e. the expected pattern) if a user is to apply `remotePatterns` (or any other sort of definitions).

My assumption is that our rules are always _additive_ to what might be explicitly defined in `nextConfig`, and the _user_ won't need to destructure things themselves in their `nextjs.config.ts` file.

If that's not what the code does, or my assumption about ideal patterns is incorrect please LMK

File: packages/next/src/config/with-snap-wp.ts [hunk 4]
```diff
@@ -106,6 +106,9 @@ const withSnapWP = async ( nextConfig?: NextConfig ): Promise< NextConfig > => {
 	setConfig();
 	const homeUrl = new URL( getConfig().homeUrl );
 
+	const userImages = ( nextConfig && nextConfig.images ) ?? {};
```
Comment (SH4LIN) [inline packages/next/src/config/with-snap-wp.ts:109]: Refactor this to nextConfig?.images ?? {};?

**Review by SH4LIN — CHANGES_REQUESTED** [review]

File: .changeset/fair-carrots-invite.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"@snapwp/next": patch
+---
+
+Bug-Fix: remote patterns in users config being ignored
```
Comment (justlevine) [inline .changeset/fair-carrots-invite.md:5]: Since these get converted to the change log, they should also use [Conventional Commits](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13)

```suggestion
fix: ensure user-defined `remotePatterns` aren't overridden by `withSnapWP()`
```

**Review by SH4LIN — APPROVED** [review]

File: packages/next/src/config/with-snap-wp.ts (hunk 1 above)
Comment (ayushnirwal) [reply packages/next/src/config/with-snap-wp.ts]: > My assumption is that our rules are always additive to what might be explicitly defined in nextConfig, and the user won't need to destructure things themselves in their nextjs.config.ts file

This assumption is correct apart from `nextConfig.images`. It was being overridden rather than being added to. This PR fixes that bug.

**Review by justlevine — APPROVED** [review]
