### PR TITLE
Fix: merge webpack config from user

### LINKED ISSUE #135: Bug: `withSnapWP()` overloads `webpack` property in `next.config.mjs`
### Description

(Reported by @kidunot89)

Currently, the `withSnapWP()` HOC overwrites any custom `NextConfig.webpack` configuration the user may provide.

Like with #113 , we need to make this both overwritable _and_ composable.

### Link to the code that reproduces this issue

https://github.com/ayushnirwal/snapwp/blob/bb813bcf925da88ed1e169dbb2f0a8ee81d4b26c/packages/next/src/config/with-snap-wp.ts#L129

### To Reproduce

1. Add a `webpack` config in `next.config.mjs` (wrapped by withSnapWP() )`
2. Confirm it has no effect.

### Additional context

Use Cases:

1. Replacing: can technically be done by (psuedocode) `withSnapWP().webpack = ...` instead of returning the HOC directly.
2. Modifying: our webpack isnt meant for extension, if they want to `use config` somewhere else or whatever, they can make their own that mimics ours.
3.  Extending: **this is the important one we need to support**, allowing ours and userland webpacks to coexist.

### Frontend Environment

```bash
N/A
```

### Backend Environment

```markdown
N/A
```

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### PR DESCRIPTION
**Pull request by ayushnirwal**
## What

Fixed webpack config not being overridable when `withSnapWP` is used to generate config for NextJS.

## Why

Currently, the withSnapWP() HOC overwrites any custom NextConfig.webpack configuration the user may provide.

### Related Issue(s):

Fixes #135 

## How

- Add a utility to get webpack plugin array `get-snap-wp-webpack-plugins.ts` .
- Update webpack function in NextJS config to allow overloading.

## Additional Info

- [snapwp-remote-patterns.ts](https://github.com/rtCamp/snapwp/pull/136/files#diff-36e9057b30b6df66e71fab54ad3356433992c5249833f2dbfae4100481375e1c)  is refactored out of [with-snap-wp.ts](https://github.com/rtCamp/snapwp/pull/136/files#diff-81ae033471ae1b50c8fb0773fdc1017ccd6478d06f8eaa70dce066abbd5c63fe)
- [get-snap-wp-config-path.ts](https://github.com/rtCamp/snapwp/pull/136/files#diff-a7ebc42b8d194f9564955cb1bf73b4da8d19ae8615de1f35c401c116aa64882f) is refactored out of [with-snap-wp.ts](https://github.com/rtCamp/snapwp/pull/136/files#diff-81ae033471ae1b50c8fb0773fdc1017ccd6478d06f8eaa70dce066abbd5c63fe)
- [get-snap-wp-webpack-plugins.ts](https://github.com/rtCamp/snapwp/pull/136/files#diff-b08476b74abed24a6eeb6edef75a5ccb52494054cebd5ee2e736aeb26f77b154) added as an utility to generate webpack plugin array.

## Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/rtCamp/snapwp/blob/develop/.github/CONTRIBUTING.md).
-   [x] My code is tested to the best of my abilities.
-   [x] My code passes all lints (ESLint, tsc, prettier etc.).
-   [x] My code has detailed inline documentation.
-   [ ] I have added unit tests to verify the code works as intended.
-   [ ] I have updated the project documentation as needed.
-   [x] I have added a changeset for this PR using `npm run changeset`.

### CODE REVIEW

File: packages/core/src/utils/deep-merge.ts [hunk 1]
```diff
@@ -0,0 +1,39 @@
+/**
+ *
+ * @param target - target object
+ * @param source - source object
+ * @return Merged object
+ */
+export default function deepMerge<
```
Comment (SH4LIN) [inline packages/core/src/utils/deep-merge.ts:7]: Would it be necessary to build our own `deepMerge` implementation, considering there are several well-established packages available on NPM for this?

- https://www.npmjs.com/package/deepmerge
- https://github.com/fastify/deepmerge
- https://lodash.com/docs/4.17.15#merge

File: packages/next/src/config/snapwp-remote-patterns.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
+import type { RemotePattern } from 'next/dist/shared/lib/image-config';
+
+/**
+ * Creates base remote patterns
+ * @param homeUrl -- WordPress Home Url
+ * @return Remote pattern array
+ */
+export const generateRemotePatterns = ( homeUrl: URL ): RemotePattern[] => {
+	return [
```
Comment (SH4LIN) [inline packages/next/src/config/snapwp-remote-patterns.ts:9]: We are not taking the user's config into account. What we fixed in this PR - https://github.com/rtCamp/snapwp/pull/113

File: packages/next/src/config/with-snap-wp.ts [hunk 3]
```diff
@@ -82,57 +16,28 @@ const modifyWebpackConfig = ( snapWPConfigPath: string ) => {
...
+	const snapWPRemotePatterns = generateRemotePatterns( homeUrl );
 
-	return {
-		...nextConfig,
+	const snapWPWebpackPlugins = getWebpackPlugins( snapWPConfigPath );
+
+	return deepMerge( nextConfig, {
 		images: {
-			// User image config is appended before default config. Otherwise default remote patterns will be overridden
-			...userImages,
```
Comment (SH4LIN) [inline packages/next/src/config/with-snap-wp.ts:121]: We are not taking the user's config into account. What we fixed in this PR - https://github.com/rtCamp/snapwp/pull/113

File: packages/next/src/config/snapwp-remote-patterns.ts [hunk 4]
```diff
@@ -0,0 +1,19 @@
+import type { RemotePattern } from 'next/dist/shared/lib/image-config';
```
[the remark this answers is not in the document]
Comment (ayushnirwal) [reply packages/next/src/config/snapwp-remote-patterns.ts:1]: There is no other way to import that type.

File: packages/core/src/utils/deep-merge.ts (hunk 1 above)
Comment (ayushnirwal) [reply packages/core/src/utils/deep-merge.ts]: The addition of deep merge is reverted.

File: packages/next/src/config/get-snap-wp-config-path.ts [hunk 5]
```diff
@@ -0,0 +1,37 @@
+import fs from 'fs';
+import path from 'path';
+import url from 'url';
+
+/**
+ * Dynamically inds path to the snapwp config file during the build process.
```
Comment (SH4LIN) [inline packages/next/src/config/get-snap-wp-config-path.ts:6]: Typo: `finds`
```suggestion
 * Dynamically finds path to the snapwp config file during the build process.
```

**Review by SH4LIN — CHANGES_REQUESTED** [review]

**Review by SH4LIN — APPROVED** [review]

**Review by justlevine — APPROVED** [review]
